### ISSUE TITLE
The split of UCF 101 dataset

### ISSUE THREAD

**Issue by eecoder-dyf** [aayushm107/VStegNET#2]
Hello,
I'm confused with the split of UCF 101 dataset in your paper. In the paper, you said “Out of all dataset videos, 10,000 are used to generate training cover, and secret pairs (total possible pairs $C_2^{10000}$ ) and remaining are used for testing", are the train/test split followed any official split file, or you split the dataset randomly?
Thanks.

**Comment by aamixsh** [comment]
Hey,
We split the data randomly. Sampled from 10000 of the videos to generate random cover/secret pairs for training, as any two videos can be used as both cover and secret. The rest (3320) are used to generate random cover/secret pairs for testing so that there is no overlap.
Hope this helps.
